name: Create milestone from new Jira version

on:
  # workflow_dispatch allows to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the Jira ticket version (ex: API-V0.0.2)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Inputs displays
        run: | 
          echo "::notice title=Workflow ran with this input: :: version=${{ github.event.inputs.version }}"

      - name: 'Convert version to milestone label (ex: API-V0.0.2 -> v0.0.2)'
        run: |
          milestone_label="v$(echo "${{ github.event.inputs.version }}" | sed 's/[^0-9.]//g')"

          echo "milestone_label=$milestone_label" >> $GITHUB_ENV

          echo -e "\033[1;32m... ✅ milestone_label=$milestone_label\033[0m"

      - name: 'Create the milestone'
        run: |
          curl -L \
          -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/maatth/GitHubActionsTriggers/milestones \
          -d "{\"title\":\"$milestone_label\",\"state\":\"open\",\"description\":\"Created automaticaly from Jira version creation\"}" \
          --silent --fail --show-error

          echo -e "\033[1;32m... ✅ pull request milestone updated\033[0m"
