# This is a basic workflow to help you get started with Actions

name: Mon workflow pour update les milestone

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      pull_request_id:
        description: 'Specify pull request id'
        required: true
      version:
        description: 'Specify the github milestone to update'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Extraire les informations du payload envoyé par Jira via Webhook
      - name: Get Jira Ticket Version
        run: |
          jira_version="v1.0.0"
          pr_number="1"
          
          echo "Jira version: $jira_version"
          echo "PR number: $pr_number"

      - name: Update GitHub PR Milestone
        run: |
          curl -u ${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_TOKEN }} \
          -X PATCH \
          -d '{"milestone": "$jira_version"}' \
          https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number
