name: Update pull request milestone from Jira issue version

on:
  # workflow_dispatch will allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      pull_request_title_prefix:
        description: 'Specify the pull request key prefix (ex: CE-4001)'
        required: true
      version:
        description: 'Specify the Jira ticket version to update (ex: API-V0.0.2)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so this job can access it
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a one-line script
        run: echo pull_request_title_prefix= ${{ github.event.inputs.pull_request_title_prefix }} version= ${{ github.event.inputs.version }}

      - name: Run a one-line script
        run: toto='toto1'

      - name: Run a one-line script
        run: echo yooo $toto

      - name: Run a one-line script
        run: echo "::debug file=app.js,line=1::Missing semicolon"

      - name: Run a one-line script
        run: echo "::warning file=app.js,line=1::Missing semicolon"

      - name: Run a one-line script
        run: echo "::notice file=app.js,line=1::Missing semicolon"

      - name: 'Convert JIRA ticket version to Github milestone number'
        id: convert-milestone-number
        run: |
          milestone_label="v$(echo "${{ github.event.inputs.version }}" | sed 's/[^0-9.]//g')"
          echo "milestone_label=$milestone_label"

          milestone_number=$(curl -L -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/maatth/GitHubActionsTriggers/milestones | jq --arg milestone_label "$milestone_label" '.[] | select(.title == $milestone_label).number')
          echo "milestone_number=$milestone_number"

          pull_request_number=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/maatth/GitHubActionsTriggers/pulls | jq --arg title_prefix "${{ github.event.inputs.pull_request_title_prefix }}" '.[] | select(.title | contains($title_prefix)).number');
          echo "pull_request_number=$pull_request_number"
          
          curl -u ${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_TOKEN }} -X PATCH -d "{\"milestone\": \"$milestone_number\"}" https://api.github.com/repos/maatth/GitHubActionsTriggers/issues/$pull_request_number;


      #   
      # Extraire les informations du payload envoyé par Jira via Webhook
      # - name: Get Jira Ticket Version
      #   run: |
      #     echo "milestone_number=$milestone_number"

      # - name: Update GitHub PR Milestone
      #   run: |
      #     curl -u ${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_TOKEN }} \
      #     -X PATCH \
      #     -d '{"milestone": "$milestone_number"}' \
      #     https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.inputs.pull_request_id }}
